# Generated by Django 4.2.21 on 2025-06-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date for these analytics', unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0, help_text='Users who logged in on this date')),
                ('new_registrations', models.PositiveIntegerField(default=0)),
                ('total_books', models.PositiveIntegerField(default=0)),
                ('available_books', models.PositiveIntegerField(default=0)),
                ('books_borrowed', models.PositiveIntegerField(default=0, help_text='Number of books borrowed on this date')),
                ('books_returned', models.PositiveIntegerField(default=0, help_text='Number of books returned on this date')),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('overdue_books', models.PositiveIntegerField(default=0)),
                ('late_fees_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('popular_categories', models.JSONField(blank=True, default=list, help_text='Top 10 popular categories')),
                ('popular_books', models.JSONField(blank=True, default=list, help_text='Top 10 popular books')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Analytics',
                'verbose_name_plural': 'System Analytics',
                'db_table': 'system_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('search', 'Book Search'), ('view', 'Book View'), ('borrow', 'Book Borrow'), ('return', 'Book Return'), ('renew', 'Book Renewal'), ('reserve', 'Book Reservation'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change')], db_index=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'db_table': 'user_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
