---
# ====================================
# Nginx Role Variables
# Web Server and Load Balancer Configuration
# Command 7: Ansible Configuration Management
# ====================================

# Nginx Basic Configuration
nginx_user: "nginx"
nginx_group: "nginx"
nginx_worker_processes: "auto"
nginx_worker_connections: 1024
nginx_worker_rlimit_nofile: 65535
nginx_error_log: "/var/log/nginx/error.log"
nginx_access_log: "/var/log/nginx/access.log"
nginx_pid: "/var/run/nginx.pid"

# Server Configuration
nginx_port: 80
nginx_ssl_port: 443
nginx_server_tokens: "off"
nginx_server_names_hash_bucket_size: 128
nginx_client_max_body_size: "20M"
nginx_client_body_timeout: "60s"
nginx_client_header_timeout: "60s"
nginx_send_timeout: "60s"
nginx_keepalive_timeout: "65s"
nginx_keepalive_requests: 100

# SSL Configuration
ssl_enabled: true
ssl_certificate_type: "self_signed"  # self_signed, letsencrypt, custom
ssl_certificate_path: "/etc/nginx/ssl/nginx-selfsigned.crt"
ssl_private_key_path: "/etc/nginx/ssl/nginx-selfsigned.key"
ssl_dhparam_path: "/etc/nginx/ssl/dhparam.pem"
generate_dhparam: true

# SSL Security Settings
ssl_protocols: "TLSv1.2 TLSv1.3"
ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
ssl_prefer_server_ciphers: "off"
ssl_session_cache: "shared:SSL:10m"
ssl_session_timeout: "10m"
ssl_session_tickets: "off"
ssl_stapling: "on"
ssl_stapling_verify: "on"

# Compression Configuration
gzip_enabled: true
gzip_vary: "on"
gzip_proxied: "any"
gzip_comp_level: 6
gzip_types:
  - "text/plain"
  - "text/css"
  - "text/xml"
  - "text/javascript"
  - "application/json"
  - "application/javascript"
  - "application/xml+rss"
  - "application/atom+xml"
  - "image/svg+xml"

# Security Headers
security_headers:
  x_frame_options: "DENY"
  x_content_type_options: "nosniff"
  x_xss_protection: "1; mode=block"
  referrer_policy: "strict-origin-when-cross-origin"
  content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:; media-src 'self'; object-src 'none'; child-src 'none'; worker-src 'none'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'"
  strict_transport_security: "max-age=31536000; includeSubDomains; preload"
  permissions_policy: "geolocation=(), microphone=(), camera=()"

# Rate Limiting Configuration
rate_limit_enabled: true
rate_limit_zones:
  api: "10m rate=100r/m"
  login: "10m rate=10r/m"
  general: "10m rate=200r/m"

# Proxy Configuration (for Django backend)
proxy_connect_timeout: "60s"
proxy_send_timeout: "60s"
proxy_read_timeout: "60s"
proxy_buffer_size: "4k"
proxy_buffers: "8 4k"
proxy_busy_buffers_size: "8k"
proxy_temp_file_write_size: "8k"

# Backend Server Configuration
backend_servers:
  - "127.0.0.1:8000"

# Load Balancer Configuration
lb_method: "least_conn"  # round_robin, least_conn, ip_hash, hash
lb_max_fails: 3
lb_fail_timeout: "30s"
lb_keepalive: 32

# Cache Configuration
proxy_cache_enabled: true
proxy_cache_path: "/var/cache/nginx"
proxy_cache_levels: "1:2"
proxy_cache_keys_zone: "app_cache:10m"
proxy_cache_max_size: "1g"
proxy_cache_inactive: "60m"
proxy_cache_use_temp_path: "off"

# Static Files Configuration
static_files_location: "/static/"
static_files_root: "/var/www/library-system/static"
static_files_expires: "30d"

media_files_location: "/media/"
media_files_root: "/var/www/library-system/media"
media_files_expires: "7d"

# Logging Configuration
log_format_main: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" $request_time'
log_format_detailed: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" $request_time $upstream_response_time $upstream_addr'

# Error Pages
custom_error_pages:
  404: "/404.html"
  500: "/500.html"
  502: "/502.html"
  503: "/503.html"
  504: "/504.html"

# Health Check Configuration
health_check_location: "/nginx-health"
status_location: "/nginx_status"

# Environment-specific Configuration
development_config:
  worker_processes: 1
  worker_connections: 512
  ssl_enabled: false
  rate_limit_enabled: false
  proxy_cache_enabled: false
  gzip_enabled: false

staging_config:
  worker_processes: 2
  worker_connections: 1024
  ssl_enabled: true
  rate_limit_enabled: true
  proxy_cache_enabled: true
  gzip_enabled: true

production_config:
  worker_processes: "auto"
  worker_connections: 2048
  ssl_enabled: true
  rate_limit_enabled: true
  proxy_cache_enabled: true
  gzip_enabled: true

# Monitoring Configuration
monitoring_enabled: true
nginx_exporter_enabled: true
nginx_exporter_port: 9113

# Backup Configuration
backup_nginx_config: true
backup_ssl_certificates: true
backup_location: "/var/backups/nginx"

# Oracle Cloud Specific Configuration
oracle_cloud_integration:
  load_balancer_integration: true
  waf_integration: true
  cdn_integration: false

# Custom Nginx Modules
nginx_modules:
  - "ngx_http_realip_module"
  - "ngx_http_headers_more_filter_module"
  - "ngx_http_geoip_module"

# Fail2ban Integration
fail2ban_nginx_filters:
  - "nginx-http-auth"
  - "nginx-noscript"
  - "nginx-badbots"
  - "nginx-noproxy"

# Performance Tuning
performance_tuning:
  open_file_cache: "max=1000 inactive=20s"
  open_file_cache_valid: "30s"
  open_file_cache_min_uses: 2
  open_file_cache_errors: "on"
  tcp_nopush: "on"
  tcp_nodelay: "on"
  sendfile: "on"
  reset_timedout_connection: "on"

# MIME Types
mime_types_file: "/etc/nginx/mime.types"
default_type: "application/octet-stream"

# Virtual Host Templates
vhost_templates:
  application: "application.conf.j2"
  loadbalancer: "loadbalancer.conf.j2"
  api: "api.conf.j2"
  static: "static.conf.j2"

# Security Configuration
security_config:
  hide_nginx_version: true
  disable_autoindex: true
  block_common_exploits: true
  whitelist_allowed_methods: ["GET", "POST", "PUT", "DELETE", "HEAD", "OPTIONS"]

# Resource Limits
resource_limits:
  worker_rlimit_nofile: 65535
  client_body_buffer_size: "128k"
  client_header_buffer_size: "1k"
  large_client_header_buffers: "4 4k"
  output_buffers: "2 32k"
  postpone_output: 1460

# Custom Configuration
custom_config_files: []
custom_server_blocks: []
custom_location_blocks: []

# Maintenance Mode
maintenance_mode:
  enabled: false
  message: "Site is under maintenance. Please try again later."
  allowed_ips: ["127.0.0.1"]
