---
# ====================================
# Database Role Variables
# Oracle Database Client Configuration
# Command 7: Ansible Configuration Management
# ====================================

# Oracle User and Directory Configuration
oracle_user: "oracle"
oracle_group: "oinstall"
oracle_base: "/opt/oracle"
oracle_home: "/opt/oracle/product/19c/client_1"
oracle_inventory: "/opt/oracle/oraInventory"
oracle_network_admin: "/opt/oracle/network/admin"
oracle_wallet_location: "/opt/oracle/wallet"

# Oracle Client Configuration
oracle_client_version: "19.0.0"
oracle_client_lib_path: "/usr/lib/oracle/19/client64/lib"
oracle_client_bin_path: "/usr/lib/oracle/19/client64/bin"

# Oracle Client Download URLs (Oracle Linux 8)
oracle_client_download_url: "https://download.oracle.com/otn_software/linux/instantclient/1919000/oracle-instantclient19.19-basic-19.19.0.0.0-1.x86_64.rpm"
oracle_sqlplus_download_url: "https://download.oracle.com/otn_software/linux/instantclient/1919000/oracle-instantclient19.19-sqlplus-19.19.0.0.0-1.x86_64.rpm"
oracle_client_rpm: "oracle-instantclient19.19-basic-19.19.0.0.0-1.x86_64.rpm"
oracle_sqlplus_rpm: "oracle-instantclient19.19-sqlplus-19.19.0.0.0-1.x86_64.rpm"

# Database Connection Configuration
database_type: "oracle"
database_service_name: "LIBRARY_HIGH"
database_user: "LIBRARY_USER"
database_password: "{{ vault_database_password }}"
database_host: "{{ autonomous_db_connection_string }}"
database_port: 1522

# Autonomous Database Configuration
autonomous_db_name: "LibraryDB"
autonomous_db_admin_password: "{{ vault_db_admin_password }}"
database_wallet_download_url: "{{ vault_wallet_download_url | default('') }}"

# TNS Names Configuration
tnsnames_entries:
  - name: "LIBRARY_HIGH"
    description: "Library Database High Performance"
    protocol: "TCP"
    host: "{{ database_host }}"
    port: "{{ database_port }}"
    service_name: "library_high"
    
  - name: "LIBRARY_MEDIUM"
    description: "Library Database Medium Performance"
    protocol: "TCP"
    host: "{{ database_host }}"
    port: "{{ database_port }}"
    service_name: "library_medium"
    
  - name: "LIBRARY_LOW"
    description: "Library Database Low Performance"
    protocol: "TCP"
    host: "{{ database_host }}"
    port: "{{ database_port }}"
    service_name: "library_low"

# SQL*Net Configuration
sqlnet_settings:
  names_directory_path: "{{ oracle_network_admin }}"
  names_default_domain: ""
  trace_level_client: "OFF"
  trace_unique_client: "ON"
  log_level_client: "OFF"
  diag_adr_enabled: "ON"
  diag_sighandler_enabled: "TRUE"
  
# Wallet Configuration
wallet_settings:
  wallet_location: "{{ oracle_wallet_location }}"
  ssl_server_dn_match: "TRUE"
  ssl_version: "1.2"
  ssl_cipher_suites: "TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256"

# Connection Pooling Configuration
connection_pooling: true
connection_pool_settings:
  min_pool_size: 2
  max_pool_size: 20
  increment: 2
  timeout: 300
  getmode: "SPOOL_ATTRVAL_FORCEGET"
  homogeneous: true

# Performance Tuning
performance_settings:
  tcp_connect_timeout: 60
  tcp_nodelay: "TRUE"
  recv_timeout: 30
  send_timeout: 30
  disable_oob: "TRUE"
  
# Security Configuration
security_settings:
  encryption_client: "ACCEPTED"
  encryption_types_client: "AES256,AES192,AES128"
  crypto_checksum_client: "ACCEPTED"
  crypto_checksum_types_client: "SHA256,SHA1"
  sqlnet_allowed_logon_version_client: 12
  sqlnet_allowed_logon_version_server: 12

# Monitoring Configuration
monitoring_enabled: true
monitoring_settings:
  check_interval: 300  # 5 minutes
  connection_timeout: 30
  query_timeout: 60
  alert_thresholds:
    response_time: 5000  # milliseconds
    connection_failures: 3
    query_failures: 5

# Backup Configuration
backup_enabled: true
backup_settings:
  backup_location: "/opt/oracle/backups"
  retention_days: 7
  compression: true
  encryption: true

# Logging Configuration
logging_settings:
  log_level: "INFO"
  log_location: "/var/log/oracle"
  log_file_size: "10MB"
  log_file_count: 5
  trace_enabled: false

# SQL*Plus Configuration
sql_plus_enabled: true
sqlplus_settings:
  pagesize: 0
  linesize: 1000
  trimspool: "ON"
  trimout: "ON"
  tab: "OFF"
  verify: "OFF"
  feedback: "OFF"
  heading: "OFF"

# Application Integration
app_user: "libraryapp"
app_group: "libraryapp"
app_home: "/opt/library-system"

# Oracle Cloud Infrastructure Integration
oci_auth_token: "{{ vault_oci_auth_token }}"
oci_region: "us-ashburn-1"
oci_compartment_id: "{{ vault_oci_compartment_id }}"

# Environment-specific Configuration
development_settings:
  connection_pool_min: 1
  connection_pool_max: 5
  monitoring_interval: 600
  log_level: "DEBUG"
  trace_enabled: true

staging_settings:
  connection_pool_min: 2
  connection_pool_max: 10
  monitoring_interval: 300
  log_level: "INFO"
  trace_enabled: false

production_settings:
  connection_pool_min: 5
  connection_pool_max: 20
  monitoring_interval: 60
  log_level: "WARNING"
  trace_enabled: false

# Test Configuration
test_queries:
  basic_connectivity: "SELECT 'Connected' FROM dual"
  performance_test: "SELECT COUNT(*) FROM user_tables"
  privilege_test: "SELECT username FROM user_users"

# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 5
  circuit_breaker_threshold: 10
  circuit_breaker_timeout: 300

# Oracle Client Environment Variables
oracle_environment:
  ORACLE_HOME: "{{ oracle_home }}"
  TNS_ADMIN: "{{ oracle_network_admin }}"
  LD_LIBRARY_PATH: "{{ oracle_client_lib_path }}:$LD_LIBRARY_PATH"
  PATH: "{{ oracle_client_bin_path }}:$PATH"
  NLS_LANG: "AMERICAN_AMERICA.UTF8"
  NLS_DATE_FORMAT: "YYYY-MM-DD HH24:MI:SS"
  NLS_TIMESTAMP_FORMAT: "YYYY-MM-DD HH24:MI:SS.FF"

# Required System Packages
required_packages:
  - libaio
  - libaio-devel
  - libnsl
  - libcrypt-compat
  - libxcrypt-compat
  - elfutils-libelf-devel
  - glibc-devel
  - gcc
  - gcc-c++
  - make
  - unzip
  - wget
  - which
  - openssl
  - openssl-devel
  - krb5-libs
  - krb5-devel
  - python3-pip
  - python3-devel

# Python Oracle Packages
python_oracle_packages:
  - cx_Oracle
  - oracledb

# Service Configuration
service_settings:
  enabled: true
  start_on_boot: true
  restart_policy: "always"
  restart_delay: 10

# Health Check Configuration
health_check:
  enabled: true
  endpoint: "/health/database"
  interval: 30
  timeout: 10
  retries: 3

# Firewall Configuration
firewall_rules:
  - port: 1521
    protocol: "tcp"
    source: "{{ ansible_default_ipv4.network }}/24"
  - port: 1522
    protocol: "tcp"
    source: "{{ ansible_default_ipv4.network }}/24"

# Audit Configuration
audit_settings:
  enabled: true
  audit_trail: "DB"
  audit_file_dest: "/opt/oracle/audit"
  audit_sys_operations: true

# Cleanup Configuration
cleanup_settings:
  remove_temp_files: true
  remove_logs_older_than: 30
  compress_old_logs: true
